#!/bin/bash
. b*/e*
lunch aosp_RMX1921-userdebug
export CCACHE_DIR=/tmp/ccache  ##use additional flags if you need(optional)
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1

ccache -M 30G
ccache -o compression=true
ccache -z
ccache -c

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	mka api-stubs-docs
	mka system-api-stubs-docs
	mka test-api-stubs-docs
}

make_rom(){
	brunch RMX1921
	zip=$(up out/target/product/RMX1921/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom &
sleep 5000 && kill "$!"
