#!/bin/bash
sudo apt install wget
MANIFEST=git://https://github.com/TenX-OS/manifest_TenX
BRANCH=eleven

mkdir -p /tmp/tenx
cd /tmp/tenx

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice.Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "Aston-Martinn"
git config --global user.email "advaithbhat9@gmail.com"

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

pwd
ls

##delete these lines, and replace with your own lines of device sauce
git clone https://github.com/Ten-X-Devices/vendor_realme_RMX1921.git -b eleven vendor/realme/RMX1921
git clone https://github.com/Ten-X-Devices/kernel_realme_sdm710.git -b eleven kernel/realme/sdm710
git clone https://github.com/Ten-X-Devices/device_realme_RMX1921.git -b eleven device/realme/RMX1921

cd /tmp/tenx
